sudo: false

language: node_js

node_js:
  - "12"
  - "13"
  - "14"
  - "15"
  - "16"
  - "node"

install:
  - npm install
  - npm install -g istanbul
  - npm install -g codecov

script:
  - istanbul cover test.js
  - codecov